version: "3.9"  # optional since v1.27.0
services:
  camunda-db:
    image: postgres:14.2
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file: ./postgres.env
  camunda-db-test:
    image: postgres:14.2
    restart: always
    ports:
      - "15433:5432"
    volumes:
      - ./postgres-test:/var/lib/postgresql/data
    env_file: ./postgres-test.env